### ISSUE TITLE
Installer complains about deprecated settings

### ISSUE THREAD

**Issue by mattock** [Puppet-Finland/puppet-puppetmaster#38]
```
Warning: Setting autosign is deprecated. 
   (location: /opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/settings.rb:1169:in `issue_deprecation_warning')
Warning: Setting ca is deprecated. 
   (location: /opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/settings.rb:1169:in `issue_deprecation_warning')
```

**Comment by mattock** [comment]
These complaints started with recent Puppet 5.x versions. These settings are in puppet.conf generated by the Foreman project's puppet modules. As Foreman needs to support Puppet 4, there may not be an easy way to make the upstream remove those settings. We may have to fork some of foreman's puppet modules or alternatively suppress these warnings by modifying the Kafo-generated puppet.conf or puppet command-line.

**Comment by mattock** [comment]
This problem can probably be circumvented by adding

    disable_warnings=deprecations

to the puppet.conf that Kafo initially creates.

**Comment by mattock** [comment]
The deprecation warnings [seem to be premature](https://groups.google.com/forum/#!topic/puppet-users/oH1EzzMHsDw).

**Comment by mattock** [comment]
Also, the deprecation warnings appear after the first installer run, when the puppet modules have already configured puppet.conf.

**Comment by mattock** [comment]
The following patch removes all warnings:
```
--- puppet_strings_module_parser.rb     2018-09-26 10:26:48.788890570 +0000
+++ puppet_strings_module_parser.rb.new 2018-09-26 10:28:52.408890570 +0000
@@ -37,7 +37,7 @@
       @file = file = File.expand_path(file)
       raise KafoParsers::ModuleName, "File not found #{file}, check your answer file" unless File.exists?(file)

-      command = "#{self.class.puppet_bin} strings generate --emit-json-stdout #{file}"
+      command = "#{self.class.puppet_bin} strings generate --format json --disable_warnings=deprecations #{file}"
       @raw_json = `#{command}`
       unless $?.success?
         raise KafoParsers::ParseError, "'#{command}' returned error\n#{@raw_json}"
```
The --format json option was introduced in puppet-strings 1.2.0. Adapting the above command depending on puppet-string version is one way to resolve this.

**Comment by mattock** [comment]
Applying the above patch seems to fail with latest gem versions. Debug and resolve.
